apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-nyikuyjg
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/jsmid/go-nyikuyjg:8f396cc7546cfa6f00d7a9a34afd5bfaead143c1@sha256:1e4d7b8ad422bb8b4694f07af645ad2024eaabdd864e8c7dff51755658963128
          name: container-image
