apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: go-nyikuyjg
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/jsmid/go-nyikuyjg:ddcf22f202649711951d29f349c34010e260f96b@sha256:ca5262690e09bd509e336023cb3a6700f2e40b766a61f9b6b2db625dffaa7ee5
        name: container-image  
